### ISSUE TITLE
How to add an image like svg?

### ISSUE THREAD

**Issue by dandgerson** [Max-Makhrov/apps-script-parallels#5]
Hello, how to add an image like svg into Apps Script Project with clasp?
I'm trying inline all of my assets with vite, but it has no results. asset not inlined.
And when i `clasp push` it declined

That's my sandbox
https://github.com/in2sql/apps-script-react-vite-boilerplate

**Comment by Max-Makhrov** [comment]
Hello,

Apps Script does not support hosting assets, you need to host an image somewhere, and use the link.

Sample:

https://raw.githubusercontent.com/Max-Makhrov/myFiles/master/Face-woman1.jpg
